### ISSUE TITLE
demo link not available

### ISSUE THREAD

**Issue by cdpapoulias** [CloudCannon/vonge-jekyll-bookshop-template#1]
Hello,

I tried viewing the https://jazzed-kale.cloudvent.net/ demo link, but it's not available. Would someone mind looking into it?

I love Jekyll and am happy to help as well!

Thank you for everything!

Dinos

**Comment by bglw** [comment]
Hi there! 👋

Sorry about that! I have fixed that demo link so it should be working again 🙂 Thanks for letting us know!
