### ISSUE TITLE
adding fabform.io to the template

### ISSUE THREAD

**Issue by fabformG** [CloudCannon/vonge-jekyll-bookshop-template#10]
Hello

Can you add https://fabform.io to your static site templates contact form

**Comment by bglw** [comment]
👋 Hi @fabformG 

The forms on our templates are configured to use [our own Form offering](https://cloudcannon.com/documentation/articles/getting-started-with-forms-on-cloudcannon/), so we aren't looking to integrate third parties into our templates directly.

We do have a contact form comparison on our ecosystem website here: [JamStack Contact Forms](https://cloudcannon.com/community/jamstack-ecosystem/contact-forms/). If you fill out the form on that page then the team that manages it can get you listed as an option.

Cheers!
