### ISSUE TITLE
Invalid pagination numbers in Blog section.

### ISSUE THREAD

**Issue by Torbikini** [CloudCannon/vonge-jekyll-bookshop-template#12]
Hello! Great work on the theme, I've been messing around with it a bit and am most likely going to use this, but I noticed that the pagination counter appears to be hard-coded to always say 1 of 1 when looking at the `components/shared/jekyll/pagination.jekyll.html` file.

I tried to figure it out myself, but I don't know enough about Jekyll yet to fix it myself. It's not a huge deal that it isn't working, but it'd be nice to get it sorted eventually.

**Comment by bglw** [comment]
👋 Hi @Torbikini 

This template is setup to use our pagination tool [Pagebreak](https://github.com/CloudCannon/pagebreak), so those page numbers will be updated after the build when Pagebreak runs. (Note the `data-pagebreak-control` attributes on the html elements)

**Comment by bglw** [comment]
My mistake! This file was misconfigured and should have been using `data-pagebreak-label`. I have updated the repository, is this now working for you?

**Comment by Torbikini** [comment]
Yes, thank you so much! I now see what I was doing wrong - I was trying to use the default Jekyll pagination module. I'll mark this as closed!
