### ISSUE TITLE
Liquid syntax error (line 1): Unknown tag 'bookshop_scss'

### ISSUE THREAD

**Issue by emitit** [CloudCannon/vonge-jekyll-bookshop-template#14]
Hello, i'm trying to set it up and run via github pages, it failes to recognize the scss in the main.scss

[Runner error](https://github.com/emitit/emitit.github.io/runs/7938077718?check_suite_focus=true)

**Comment by bglw** [comment]
Hello 👋 

I can't see that link, but I assume it's a similar issue as #5 in that the default GitHub pages environment doesn't support custom plugins. Another good place to look would be the new actions pages workflows here: https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/

Let me know if this matches your current setup, though, and I'll re-open & investigate
