### ISSUE TITLE
BUNDLE_GEMFILE

### ISSUE THREAD

**Issue by MakiniMakini** [CloudCannon/vonge-jekyll-bookshop-template#20]
> jekyll
> BUNDLE_GEMFILE=site/Gemfile bundle exec jekyll serve --source site --port 6060 --trace --unpublished

'BUNDLE_GEMFILE' is not recognized as an internal or external command,
operable program or batch file.

Issue with this error, when I run npm start

**Comment by jwig22** [comment]
when I run the command:
`npm run install-jekyll`

I get this response in the powershell terminal in VSCode

> install-jekyll
> BUNDLE_GEMFILE=site/Gemfile bundle install
>
>'BUNDLE_GEMFILE' is not recognized as an internal or external command,
operable program or batch file.

I would like to be able to deploy this on GitHub Pages rather than rely on CloudCannon.

**Comment by myanch200** [comment]
Do you have ruby installed ? All the package json file is doing is to run ruby commands to download the dependencies and the run the server etc. Since Jekyll is built with ruby you would need to have it installed.

**Comment by ghost** [comment]
Probably not a best practice, but moving Gemfile from /site to its parent directory, run `bundle install` then run `bundle exec jekyll serve --source site --port 6060 --trace --unpublished` seems working for me on windows

**Comment by kate-ferguson** [comment]
Hey there! Thanks for raising this issue with us - if you're using windows, I would suggest to cd into site, and then run `bundle install`. Hope this helps!
