### ISSUE TITLE
Deploy thanks to Github action

### ISSUE THREAD

**Issue by arnolanglade** [CloudCannon/vonge-jekyll-bookshop-template#22]
Hi,

I revamp my website with this template and I tried to deploy it thanks to GitHub actions but I got a lot of  permission errors :

```
Configuration file: /github/workspace/site/_config.yml
          Bookshop: Parsing Stories from /github/workspace/components/components
          Bookshop: ❌ Error Parsing Story: Permission denied - /tmp/node_runner20230320-2177-164uv6xjs
                    Permission denied - /tmp/node_runner20230320-2177-164uv6xjs
          Bookshop: ❌ Error Parsing Story: Permission denied - /tmp/node_runner20230320-2177-io84lcjs
                    Permission denied - /tmp/node_runner20230320-2177-io84lcjs
          Bookshop: ❌ Error Parsing Story: Permission denied - /tmp/node_runner20230320-2177-1s4xls4js
                    Permission denied - /tmp/node_runner20230320-2177-1s4xls4js
          Bookshop: ❌ Error Parsing Story: Permission denied - /tmp/node_runner20230320-2177-pq21f1js
                    Permission denied - /tmp/node_runner20230320-2177-pq21f1js
          Bookshop: ❌ Error Parsing Story: Permission denied - /tmp/node_runner20230320-2177-zg71q5js
                    Permission denied - /tmp/node_runner20230320-2177-zg71q5js
          Bookshop: ❌ Error Parsing Story: Permission denied - /tmp/node_runner20230320-2177-5jzvxvjs
          Bookshop: ❌ Error Parsing Story: Permission denied - /tmp/node_runner20230320-2177-c2x7vmjs
```

Here is the full build: https://github.com/arnolanglade/arnolanglade.github.io/actions/runs/4473071177/jobs/7859995346

I tried https://github.com/helaili/jekyll-action and https://github.com/jeffreytse/jekyll-deploy-action and I got those errors.

I don't understand why Bookshop tries to write things in /tmp.

Thanks for your help.

**Comment by arnolanglade** [comment]
I found a solution thanks to this article https://michaelcurrin.github.io/code-cookbook/recipes/ci-cd/github-actions/workflows/jekyll/build/container.html.

Here is a working [GitHub workflow](https://github.com/arnolanglade/arnolanglade.github.io/blob/master/.github/workflows/build-jekyll.yml).

**Comment by adriguerra** [comment]
Thanks for sharing your workflow @arnolanglade 
I just want to point out to anyone who may try replicating it that all .toml files from the components folder were deleted for it to run successfully (even though locally the build seems to work for me). 

Also, for the first deployment run you may need to do the following: https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#%EF%B8%8F-first-deployment-with-github_token

**Comment by PrakritTyagi** [comment]
Thanks for your workflow @arnolanglade and @adriguerra for further information.

My workflow failed and presented with this error on using the above workflow without any changes to it and to the repo. Locally building the repo on ubuntu I had no issue.

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/main.scss':
                    Broken pipe
                    ------------------------------------------------
      Jekyll 4.3.3   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/usr/gem/gems/sass-embedded-1.63.6/lib/sass/embedded/varint.rb:35:in `write': Broken pipe (Errno::EPIPE)
```

It seems there is a issue with the docker image and sass-converter and there has been no movement to fix it
[https://github.com/jekyll/jekyll-sass-converter/issues/156](https://github.com/jekyll/jekyll-sass-converter/issues/156)
[https://github.com/envygeeks/jekyll-docker/issues/363](https://github.com/envygeeks/jekyll-docker/issues/363)

Solution is to use this docker image [https://hub.docker.com/r/jvconseil/jekyll-docker](https://hub.docker.com/r/jvconseil/jekyll-docker)
