### ISSUE TITLE
How to add katex support?

### ISSUE THREAD

**Issue by ozgunozerk** [CloudCannon/vonge-jekyll-bookshop-template#24]
I want to be able to write and render Tex (math equations). However, this template does not support it by default. 
I was able to change my previous jekyll theme (norlin) via adding katex support. But don't know how to do it for this template :/

**Comment by bglw** [comment]
If you're looking at the [jekyll-katex plugin](https://github.com/linjer/jekyll-katex), you should be able to follow its installation instructions to add it to the `site/_config.yml` and `site/Gemfile` files in this repo.

Feel free to reopen if that doesn't work out for you, but it should function the same as adding it to your other theme 🙂
