### ISSUE TITLE
Unable to set additional icons

### ISSUE THREAD

**Issue by Midnight1938** [CloudCannon/vonge-jekyll-bookshop-template#26]
While the icons listed for 'social' work fine, I am unable to add additional icons

**Comment by adriguerra** [comment]
@Midnight1938 Could you specify your code and how you tried to add additional icons?

**Comment by kate-ferguson** [comment]
Hey @Midnight1938, thanks for your question! What icons are you trying to add? Are they from [Ionicons](https://ionic.io/ionicons/v4)?

**Comment by Midnight1938** [comment]
> Hey @Midnight1938, thanks for your question! What icons are you trying to add? Are they from [Ionicons](https://ionic.io/ionicons/v4)? 

I was trying to add icons for Matrix. But have since switched to building the site without jekyll

**Comment by kate-ferguson** [comment]
> > Hey @Midnight1938, thanks for your question! What icons are you trying to add? Are they from [Ionicons](https://ionic.io/ionicons/v4)?
> 
> I was trying to add icons for Matrix. But have since switched to building the site without jekyll

Okay great, thanks for letting me know. Please reach out if you have any other issues 😃 Thanks!
