### ISSUE TITLE
Adding a custom bookshop component

### ISSUE THREAD

**Issue by Phues** [CloudCannon/vonge-jekyll-bookshop-template#35]
How do I add a custom bookshop component? I tried creating a component folder with .yaml, .html, .scss files. After that I added the bookshop section to index.html and added my component to collections in config.yaml but it doesn't work. What am I missing?

**Comment by Yoda-Soda** [comment]
From the [docs](https://github.com/CloudCannon/bookshop/blob/main/guides/jekyll.adoc). A nice and easy way to generate a new component: 

> We’ll cover creating these components soon — if you want to add a new component now, you can run npx @bookshop/init --component <name> in your Bookshop directory to scaffold it out automatically.

**Comment by Phues** [comment]
Yes I did that, similar to testimonials I am trying to generate an education-card and education-section component however after doing all the steps mentioned above my education cards are not showing  

here's the education-card component: https://github.com/Phues/portfolio/tree/main/component-library/components/education-card
education-section component: https://github.com/Phues/portfolio/tree/main/component-library/components/educations-section
