### ISSUE TITLE
How can I add additional sections?

### ISSUE THREAD

**Issue by mircea-pavel-anton** [CloudCannon/vonge-jekyll-bookshop-template#8]
On the website I am building using this theme, I want to have a Blog section as well as an Articles section.

How I would see this working is the articles would render the pages identically to the blog, only that it would pull its content from `./site/collections/_articles` instead of `./site/collections/_posts`. How should I proceed to achieve that?

I was thinking maybe specifying a source directory for the blog-related components would be a neat feature. Something like using `_posts` by default but allowing the user to override it?

**Comment by bglw** [comment]
Hello — apologies, this was overlooked. Are you still looking for a solution here?

**Comment by mircea-pavel-anton** [comment]
Hi! No problem.

I managed to do it by copying what has been done for the projects section and adapting it!

Thank you anyway!
