### ISSUE TITLE
 invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by severus-tux** [CloudCannon/vonge-jekyll-bookshop-template#9]
I tried removing the Gemfile.lock and reinstalling. I updated my `npm` and `ruby` as well. The error still persists. 

`npm: 8.3.1`
`ruby: ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]`

I get the following error when I run `npm run install-jekyll`
```
vishwa@rick2:~/vonge-jekyll-bookshop-template$ npm run install-jekyll

> install-jekyll
> BUNDLE_GEMFILE=site/Gemfile bundle install

Fetching https://github.com/CloudCannon/jekyll-watch

[!] There was an error while loading `jekyll-watch.gemspec`: invalid byte sequence in US-ASCII. Bundler cannot continue.

 #  from /home/vishwa/.gem/bundler/gems/jekyll-watch-d220b890e179/jekyll-watch.gemspec:15
 #  -------------------------------------------
 #  
 >    spec.files         = `git ls-files -z`.split("\x0").grep(%r!(bin|lib)/!)
 #    spec.executables   = spec.files.grep(%r!^bin/!) { |f| File.basename(f) }
 #  -------------------------------------------
vishwa@rick2:~/vonge-jekyll-bookshop-template$
```

_Originally posted by @severus-tux in https://github.com/CloudCannon/vonge-jekyll-bookshop-template/issues/7#issuecomment-1049203537_

**Comment by kate-ferguson** [comment]
Hey there! Thanks for raising this issue - we have updated the dependencies for this template in our last PR, so this should be fixed now. Thanks!
